# Generated by Django 2.2 on 2021-06-18 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='updated',
            new_name='update',
        ),
    ]
